# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Install Docker
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        key:  ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl gnupg lsb-release -y
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
          sudo usermod -aG docker $USER
          apt-get install make -y
          curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
          sha256sum go1.16.7.linux-amd64.tar.gz
          sudo tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
          touch ~/.profile
          echo 'export PATH=$PATH:/usr/local/go/bin' >>~/.profile
          source ~/.profile
          go version

          
    - name: prepare images
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        command_timeout: 400m
        timeout: 500m
        key:  ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          git clone --recurse-submodules --remote-submodules https://github.com/deepfence/ThreatMapper.git
          cd /root/ThreatMapper
          export IMAGE_REPOSITORY=deepfenceio
          env DF_IMG_TAG=action
          sh build.sh
          
          
      
    
